#!/usr/bin/env bash

# $1 - Git repository name
# $2 - Branch name
startup() {
    echo "Watch started: $*"
}

# $1 - Git repository name
# $2 - Branch name
no_changes() {
    echo "Nothing changed: $*"
}


# $1 - Git repository name
# $2 - Branch name
has_changes() {
    cd /home/forge/supermercadonow.com
    OUTPUT=$(git pull)

    if echo $OUTPUT | grep "composer.json\|composer.lock" >/dev/null 2>&1
    then
        composer install --no-interaction --no-dev --prefer-dist
    fi

    if $IS_MASTER
    then
        if echo $OUTPUT | grep "migrations" >/dev/null 2>&1
        then
            php artisan migrate --force
        fi
        
        php artisan queue:restart
    fi
    
    php artisan clear-compiled
    php artisan view:clear
    php artisan config:clear
    php artisan route:clear
    php artisan auth:clear-resets
    composer dump-autoload
}

# $1 - Git repository name
# $2 - Branch name
# $3 - Commit details
change_pulled() {
    echo "Changes pulled: $*"
}

# $1 - Git repository name
# $2 - Branch name
# $3 - Commit details
pull_failed() {
    echo "Pull failed --> Exiting: $*"
    exit 1
}

# $1 - Git repository name
# $2 - New branch name
# $3 - Old branch name
branch_changed() {
    echo "Branch changed: $*"
}

# $1 - Git repository name
# $2 - Branch name
upstream_not_set() {
    echo "Upstream not set: $*"
}

# $1 - Git repository name
# $2 - Branch name
local_change() {
    echo "local file changed: $*"
}

# $1 - Git repository name
# $2 - Branch name
diverged() {
    echo "Diverged --> Exiting: $*"
    exit 1
}
